### ISSUE TITLE
Despite generation of new /etc/caddy/Caddyfile, cert for new container is not generated

### ISSUE THREAD

**Issue by noisy** [wemake-services/caddy-gen#13]
So I added this entry to docker compose
```
  sslwykop2:
    image: "katacoda/docker-http-server:v2"
    labels:
      - "virtual.host=test2.ssl-wykop.pl"  # your domains separated with a space
      - "virtual.port=80"  # exposed port of this container
      - "virtual.tls-email=my@email.com"  # ssl is now on
      - "virtual.websockets" # enable websocket passthrough
```

It works, but not without restarting caddy-gen container. Logs without restarting caddy:

```
caddy-gen    | caddy.1    | https://ssl-wykop.pl
caddy-gen    | caddy.1    | 2018/09/14 01:49:11 https://ssl-wykop.pl
caddy-gen    | caddy.1    | https://test.ssl-wykop.pl
caddy-gen    | caddy.1    | 2018/09/14 01:49:11 https://test.ssl-wykop.pl
caddy-gen    | caddy.1    | http://ssl-wykop.pl
caddy-gen    | caddy.1    | 2018/09/14 01:49:11 http://ssl-wykop.pl
caddy-gen    | caddy.1    | http://test.ssl-wykop.pl
caddy-gen    | caddy.1    | 2018/09/14 01:49:11 http://test.ssl-wykop.pl
caddy-gen    | caddy.1    | 188.121.0.11 - - [14/Sep/2018:01:49:15 +0000] "GET / HTTP/2.0" 200 103
caddy-gen    | caddy.1    | 188.121.0.11 - - [14/Sep/2018:01:49:16 +0000] "GET /favicon.ico HTTP/2.0" 200 79
caddy-gen    | dockergen.1 | 2018/09/14 01:51:33 Received event start for container 135aedd5d062
caddy-gen    | dockergen.1 | 2018/09/14 01:51:33 Debounce minTimer fired
caddy-gen    | dockergen.1 | 2018/09/14 01:51:33 Generated '/etc/caddy/Caddyfile' from 10 containers
caddy-gen    | caddy.1    | 2018/09/14 01:51:53 http: TLS handshake error from 188.121.0.11:41824: no certificate available for test2.ssl-wykop.pl
caddy-gen    | caddy.1    | 2018/09/14 01:51:53 http: TLS handshake error from 188.121.0.11:41826: no certificate available for test2.ssl-wykop.pl

```
