### ISSUE TITLE
Add virtual.alias

### ISSUE THREAD

**Issue by ro31337** [wemake-services/caddy-gen#6]
It would be nice to have `virtual.alias` option.

For example, I can specify:

```
  whoami:  # this is your service
    image: "katacoda/docker-http-server:v2"
    labels:
      - "virtual.host=myapp.com"  # your domain
      - "virtual.alias=www.myapp.com"  # optional redirect
      - "virtual.port=80"  # exposed port of this container
      - "virtual.tls-email=admin@myapp.com"  # ssl is now on
```

And Caddy will redirect from alias to the main host. If my main website is `www.myapp.com`, config will look like:

```
  whoami:  # this is your service
    image: "katacoda/docker-http-server:v2"
    labels:
      - "virtual.host=www.myapp.com"  # your domain
      - "virtual.alias=myapp.com"  # optional redirect
      - "virtual.port=80"  # exposed port of this container
      - "virtual.tls-email=admin@myapp.com"  # ssl is now on
```

Now if I specify `www` and visit `myapp.com` (without prefix), I get the following error:

> 404 Site backdoor-busters.com is not served on this interface

Which is not cool (also, don't be confused, seems like if the domain is not your cache, it can redirect for some reason).
