### ISSUE TITLE
Automatic detection of localhost

### ISSUE THREAD

**Issue by bedax** [wemake-services/caddy-gen#63]
Hello, I have a `docker-compose.yml` file which I want to be largely static, such that a user wouldn't need to edit it. I then have a `.env` file where the user can add their specific details, like their email address.

So let's say `.env` contains:

```
DOMAIN=localhost
EMAIL=bob@somewhere.com
```

And the `docker-compose.yml` contains:

```
services:
  service:
    labels:
      virtual.tls: $EMAIL
      virtual.host: $DOMAIN
      virtual.port: 80
```

I currently get the following error:

```
Obtain: subject does not qualify for a public certificate: localhost
```

So I have to set `EMAIL=internal` for it to work. Unless I'm missing something (which is possible; I'm new to docker), it would be nice if it could be detected that given the `virtual.host` is `localhost`, `virtual.tls` must be `internal`.
